language: node_js
node_js:
    - lts/*
jobs:
    fast_finish: true
install:
    # - npm install -g istanbul
    - npm install -g codecov
    - npm i -D nyc@15.1.0
script:
    # - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
    - npm run report-coverage
after_success: npm run test && npm run coverage