language: node_js
node_js:
    - lts/*
jobs:
    fast_finish: true
install:
    - npm install -g codecov
script:
    # - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
    - nyc mocha --report lcovonly -- -R spec && codecov
    - codecov