language: node_js
node_js:
    - lts/*
jobs:
    fast_finish: true
install:
    - npm install
    - npm install -g codecov
script:
    - nyc mocha --report lcovonly -- -R spec && codecov
    - codecov